spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shishan_shike?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: chengzi0812

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sssk.entity
  configuration:
    map-underscore-to-camel-case: true