/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./components/layout/AdminLayout.vue')['default']
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    Appheader: typeof import('./components/common/Appheader.vue')['default']
    BlankLayout: typeof import('./components/layout/BlankLayout.vue')['default']
    Breadcrumb: typeof import('./components/common/Breadcrumb.vue')['default']
    DishCard: typeof import('./components/cards/DishCard.vue')['default']
    MainLayout: typeof import('./components/layout/MainLayout.vue')['default']
    NutritionChart: typeof import('./components/charts/NutritionChart.vue')['default']
    PlanCard: typeof import('./components/cards/PlanCard.vue')['default']
    PostCard: typeof import('./components/cards/PostCard.vue')['default']
    ProgressChart: typeof import('./components/charts/ProgressChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/common/SideMenu.vue')['default']
    TrendChart: typeof import('./components/charts/TrendChart.vue')['default']
  }
}
